version: '3'
services:
  raphael_backend_flask:
    image: fullfact/raphael-backend:latest
    environment:
      - DB_PATH=/app/db/database.db
      - PROXY_COUNT=${PROXY_COUNT}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - PROXY_DOMAIN=${PROXY_DOMAIN}
    volumes:
      - backend-data:/app/db
    ports:
      - "3000:3000"

volumes:
  backend-data:
