version: '3'
services:
  raphael_backend_flask:
    image: fullfact/raphael-backend:latest
    environment:
      - DB_PATH=/app/db/database.db
    volumes:
      - backend-data:/app/db
    ports:
      - "3000:3000"

volumes:
  backend-data:
