version: '3'
services:
  raphael_frontend_react:
    image: raphael/frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4000:80"

  raphael_backend_flask:
    image: raphael/backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - DB_PATH=/app/data/database.db
    volumes:
      - backend-data:/app/data
    ports:
      - "3000:3000"

volumes:
  backend-data:
