---
- hosts: all
  become: true

  tasks:
    - name: Copy Compose file
      copy:
        src: "{{ playbook_dir }}/../../compose.yaml"
        dest: compose.yaml

    - name: Log into DockerHub
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_token }}"

    - name: Run docker compose up
      command: REGISTRY=docker.io/ docker compose up -d
