---
- hosts: all
  become: true

  tasks:
    - name: Copy Compose file
      copy:
        src: "{{ playbook_dir }}/../../compose.yaml"
        dest: compose.yaml

    # - name: Log into DockerHub
    #   docker_login:
    #     username:
    #     password:

    - name: Run docker compose up
      command: docker compose up -d --force-recreate
