---
- hosts: all
  become: true
  vars:
    nginx_conf_path: /etc/nginx/sites-available/reverse-proxy.conf
    ssl_cert_path: /etc/letsencrypt/live/raphael.fullfact.org/fullchain.pem
    ssl_key_path: /etc/letsencrypt/live/raphael.fullfact.org/privkey.pem

    certbot_create_if_missing: true
    certbot_admin_email: afc@fullfact.org
    certbot_certs:
      - domains:
          - raphael.fullfact.org
    certbot_create_standalone_stop_services:
      - nginx

  roles:
    - geerlingguy.certbot

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - openssl
          - python3-cryptography>=1.3
        update_cache: true

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-rootless-extras
          - docker-compose-plugin
        update_cache: true

    - name: Install Nginx
      apt:
        name: nginx
        update_cache: true

    - name: Configure Nginx reverse proxy
      blockinfile:
        path: "{{ nginx_conf_path }}"
        create: true
        block: |
          server {
              listen 80;
              server_name 0.0.0.0;
              return 301 https://$server_name$request_uri;
          }

          server {
              listen 443 ssl;
              server_name 0.0.0.0;

              ssl_certificate {{ ssl_cert_path }};
              ssl_certificate_key {{ ssl_key_path }};

              location / {
                  proxy_pass http://127.0.0.1:4000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Enable Nginx configuration
      file:
        src: "{{ nginx_conf_path }}"
        dest: /etc/nginx/sites-enabled/reverse-proxy.conf
        state: link

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
        daemon_reload: true
